
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'SLR'

_lr_signature = "\x17\x1d\xc4\x80'\x8d\xce6\xed\xd4\x17\x85\xb8&gw"
    
_lr_action_items = {'RPAREN':([2,3,5,9,10,11,12,],[-5,-7,-3,12,-2,-4,-6,]),'NUMBER':([0,6,7,8,],[3,3,3,3,]),'TIMES':([2,3,5,10,11,12,],[-5,-7,8,8,-4,-6,]),'PLUS':([1,2,3,5,9,10,11,12,],[7,-5,-7,-3,7,-2,-4,-6,]),'LPAREN':([0,6,7,8,],[6,6,6,6,]),'$end':([1,2,3,4,5,10,11,12,],[-1,-5,-7,0,-3,-2,-4,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'P':([0,],[4,]),'E':([0,6,],[1,9,]),'T':([0,6,7,],[5,5,10,]),'F':([0,6,7,8,],[2,2,2,11,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> P","S'",1,None,None,None),
  ('P -> E','P',1,'p_term_factor','calcparse.py',9),
  ('E -> E PLUS T','E',3,'p_expression_plus','calcparse.py',12),
  ('E -> T','E',1,'p_term_facto','calcparse.py',15),
  ('T -> T TIMES F','T',3,'p_term_times','calcparse.py',18),
  ('T -> F','T',1,'p_term_fact','calcparse.py',21),
  ('F -> LPAREN E RPAREN','F',3,'p_factor_expr','calcparse.py',24),
  ('F -> NUMBER','F',1,'p_factor_num','calcparse.py',27),
]
